hive-syncset-pause: Be more self-sufficient for v4 Hive clusters
With production environment clusters now cached, deferring to the
bastion host is only necessary for v3 Hive clusters.

diff --git a/files/bin/hive-syncset-pause b/files/bin/hive-syncset-pause
--- a/files/bin/hive-syncset-pause
+++ b/files/bin/hive-syncset-pause
@@ -18,45 +18,45 @@ then
 fi
 HIVE_CLUSTER_NAME=${2:-$(hive-cluster-name $OCM_CLUSTERID)}
 
-case $(hostname)
-in
-  bastion-nasa-*.ops.openshift.com)
-    case $HIVE_CLUSTER_NAME
-    in
-      # Hive clusters hosted on OSDv3
-      hive-integration|hive-production|hive-stage)
+case $HIVE_CLUSTER_NAME in
+  # Hive clusters hosted on OSDv3
+  hive-integration|hive-production|hive-stage)
+    case $(hostname) in
+      bastion-nasa-*.ops.openshift.com)
         OC="ssh root@${HIVE_CLUSTER_NAME}-master -o StrictHostKeyChecking=no oc"
         ;;
       *)
-        SOCKET_DIR=$XDG_RUNTIME_DIR/ssh
-        mkdir --parents $SOCKET_DIR
-        CONTROL_PATH="$SOCKET_DIR/%h.sock"
-        HIVE_CLUSTER_ID=$(get-cluster-var $HIVE_CLUSTER_NAME id)
-        ADDRESS=$(sshaddress $HIVE_CLUSTER_ID)
-        PROXY_PORT=$(find-proxy-port $HIVE_CLUSTER_ID)
-        trap "ssh -q -O exit -o ControlPath=$CONTROL_PATH $ADDRESS" EXIT
-        ssh -4fq -D $PROXY_PORT -o ControlMaster=yes -o ControlPath=$CONTROL_PATH $ADDRESS true > /dev/null
-        export HTTPS_PROXY=socks5://localhost:$PROXY_PORT
-        OC="oc --config=$XDG_CONFIG_HOME/ocm/production/clusters/$HIVE_CLUSTER_NAME"
-        # Need to be (temporarily) in osd-sre-cluster-admins to annotate.
-        $OC adm groups add-users osd-sre-cluster-admins $($OC whoami)
+        # Defer to the bastion host.
+        exit $(ssh bastion-nasa-1.ops.openshift.com bin/$(basename $0) $OCM_CLUSTERID $HIVE_CLUSTER_NAME)
         ;;
     esac
-
-    SELECTOR=api.openshift.com/id=$OCM_CLUSTERID
-    ANNOTATION=hive.openshift.io/syncset-pause="true"
-
-    HIVE_NAMESPACE=$($OC get clusterdeployment --all-namespaces --selector $SELECTOR --output json | jq --raw-output '.items[0].metadata.namespace')
-    if [[ -z "$HIVE_NAMESPACE" ]]
-    then
-      echo "ClusterDeployment $OCM_CLUSTERID not found on $HIVE_CLUSTER_NAME" > /dev/stderr
-      exit 1
-    fi
-
-    $OC annotate clusterdeployment --namespace $HIVE_NAMESPACE --selector $SELECTOR --overwrite $ANNOTATION
     ;;
+
   *)
-    # Defer to the bastion host, which can access production Hive clusters.
-    ssh bastion-nasa-1.ops.openshift.com bin/$(basename $0) $OCM_CLUSTERID $HIVE_CLUSTER_NAME
+    SOCKET_DIR=$XDG_RUNTIME_DIR/ssh
+    mkdir --parents $SOCKET_DIR
+    CONTROL_PATH="$SOCKET_DIR/%h.sock"
+    HIVE_CLUSTER_ID=$(get-cluster-var $HIVE_CLUSTER_NAME id)
+    OCM_PRODUCTION_DIR="$XDG_CONFIG_HOME/ocm/production"
+    ADDRESS=$(OCM_CONFIG="$OCM_PRODUCTION_DIR/config" sshaddress $HIVE_CLUSTER_ID)
+    PROXY_PORT=$(find-proxy-port $HIVE_CLUSTER_ID)
+    trap "ssh -q -O exit -o ControlPath=$CONTROL_PATH $ADDRESS" EXIT
+    ssh -4fq -D $PROXY_PORT -o ControlMaster=yes -o ControlPath=$CONTROL_PATH $ADDRESS true > /dev/null
+    export HTTPS_PROXY=socks5://localhost:$PROXY_PORT
+    OC="oc --config=$OCM_PRODUCTION_DIR/clusters/$HIVE_CLUSTER_NAME"
+    # Need to be (temporarily) in osd-sre-cluster-admins to annotate.
+    $OC adm groups add-users osd-sre-cluster-admins $($OC whoami)
     ;;
 esac
+
+SELECTOR=api.openshift.com/id=$OCM_CLUSTERID
+ANNOTATION=hive.openshift.io/syncset-pause="true"
+
+HIVE_NAMESPACE=$($OC get clusterdeployment --all-namespaces --selector $SELECTOR --output json | jq --raw-output '.items[0].metadata.namespace')
+if [[ -z "$HIVE_NAMESPACE" ]]
+then
+  echo "ClusterDeployment $OCM_CLUSTERID not found on $HIVE_CLUSTER_NAME" > /dev/stderr
+  exit 1
+fi
+
+$OC annotate clusterdeployment --namespace $HIVE_NAMESPACE --selector $SELECTOR --overwrite $ANNOTATION
