hive-kubeadmin: Update to handle private OSDv4 Hive clusters

diff --git a/files/bin/hive-kubeadmin b/files/bin/hive-kubeadmin
--- a/files/bin/hive-kubeadmin
+++ b/files/bin/hive-kubeadmin
@@ -3,7 +3,9 @@
 # Retrieves the Kubernetes configuration for the cluster's admin user.
 #
 
-function get-hive-cluster {
+set -euo pipefail
+
+function get-hive-cluster-name {
   CLOUD_PROVIDER=$(ocm get /api/clusters_mgmt/v1/clusters/$1 | jq --raw-output '.cloud_provider.id')
 
   case $CLOUD_PROVIDER
@@ -30,26 +32,35 @@ then
   echo "Usage: $0 <ocm-clusterid> [hive-cluster-name]" > /dev/stderr
   exit 1
 fi
-HIVE_CLUSTER=${2:-$(get-hive-cluster $OCM_CLUSTERID)}
+HIVE_CLUSTER_NAME=${2:-$(get-hive-cluster-name $OCM_CLUSTERID)}
 
 case $(hostname)
 in
   bastion-nasa-*.ops.openshift.com)
-    case $HIVE_CLUSTER
+    case $HIVE_CLUSTER_NAME
     in
       # Hive clusters hosted on OSDv3
       hive-integration|hive-production|hive-stage)
-        OC="ssh root@${HIVE_CLUSTER}-master -o StrictHostKeyChecking=no oc"
+        OC="ssh root@${HIVE_CLUSTER_NAME}-master -o StrictHostKeyChecking=no oc"
         ;;
       *)
-        OC="oc --config=$HOME/.config/sre/clusters/v4/$HIVE_CLUSTER"
+        SOCKET_DIR=$XDG_RUNTIME_DIR/ssh
+        mkdir --parents $SOCKET_DIR
+        CONTROL_PATH="$SOCKET_DIR/%h.sock"
+        HIVE_CLUSTER_ID=$(get-cluster-var $HIVE_CLUSTER_NAME id)
+        ADDRESS=$(sshaddress $HIVE_CLUSTER_ID)
+        PROXY_PORT=$(find-proxy-port $HIVE_CLUSTER_ID)
+        trap "ssh -q -O exit -o ControlPath=$CONTROL_PATH $ADDRESS" EXIT
+        ssh -4fq -D $PROXY_PORT -o ControlMaster=yes -o ControlPath=$CONTROL_PATH $ADDRESS true > /dev/null
+        export HTTPS_PROXY=socks5://localhost:$PROXY_PORT
+        OC="oc --config=$HOME/.config/sre/clusters/v4/$HIVE_CLUSTER_NAME"
         ;;
     esac
 
     HIVE_NAMESPACE=$($OC get clusterdeployment --all-namespaces --selector=api.openshift.com/id=$OCM_CLUSTERID --output json | jq --raw-output '.items[0].metadata.namespace')
     if [[ "$HIVE_NAMESPACE" == "null" ]]
     then
-      echo "ClusterDeployment $OCM_CLUSTERID not found on $HIVE_CLUSTER" > /dev/stderr
+      echo "ClusterDeployment $OCM_CLUSTERID not found on $HIVE_CLUSTER_NAME" > /dev/stderr
       exit 1
     fi
 
@@ -57,6 +68,6 @@ in
     ;;
   *)
     # Defer to the bastion host, which can access production Hive clusters.
-    ssh bastion-nasa-1.ops.openshift.com bin/$(basename $0) $OCM_CLUSTERID $HIVE_CLUSTER
+    ssh bastion-nasa-1.ops.openshift.com bin/$(basename $0) $OCM_CLUSTERID $HIVE_CLUSTER_NAME
     ;;
 esac
